# Site settings
title: InsteadMan
email: jhekasoft@gmail.com
description: InsteadMan is manager for INSTEAD games
baseurl: "/insteadman" # the subpath of your site, e.g. /blog/
url: "http://jhekasoft.github.io/insteadman/" # the base hostname & protocol for your site
twitter_username: jhekasoft
github_username:  jhekasoft
githubUrl: https://github.com/jhekasoft/insteadman
discussionUrl: http://instead-games.ru/forum/index.php?p=/discussion/175/instead-manager
releasesUrl: https://github.com/jhekasoft/insteadman/releases
projectVersion: 2.1.0
lastReleaseDate: 2018-03-01
asset_version: 4

downloads:
  windows:
    url: https://github.com/jhekasoft/insteadman/releases/download/v2.1.0/insteadman-2.1.0.exe
    archiveUrl: https://github.com/jhekasoft/insteadman/releases/download/v2.1.0/InsteadMan-win-2.1.0-x86.zip
  macos:
    url: https://github.com/jhekasoft/insteadman/releases/download/v2.1.0/InsteadMan-2.1.0.dmg
  linux:
    url: https://github.com/jhekasoft/insteadman/releases/download/v2.1.0/insteadman_2.1.0-x64.tar.gz
    x86url: https://github.com/jhekasoft/insteadman/releases/download/v2.1.0/insteadman_2.1.0-x86.tar.gz

t:
  en:
    about: About
    other: Other
    discussion: Discussion
    toUp: Up
    insteadmanSubtitle: Play text adventures for INSTEAD!
    installInsteadman: Install InsteadMan
    windowsDownloadText: Presented by <strong>exe</strong>-installation file. Just install and play.
    windowsDownloadText2: Also available <a href="_downloadUrl_">ZIP archive</a> (run <strong>insteadman.exe</strong>).
    macosDownloadText: Presented by <strong>dmg</strong> image. Open and drag it to the <strong>Applications</strong> folder.
    linuxDownloadText: Presented by archive with binaries. Please select proper archive for your OS. Then run <strong>./insteadman</strong>.<br>You should have installed <a href="_insteadUrl_">INSTEAD <span class="glyphicon glyphicon-link"></span></a>.
    download: Download
    result: Result
    resultText: You are able to install and play games easy!
    siteSupport: Site support
    insteadSiteUrl: http://instead.syscall.ru/index.html
    releaseNotes: "<ul><li>fixed bug where a game would not install and run on Windows OS;</li><li>changed games sorting: URQ-games at the end;</li><li>fixed other small bugs.</li></ul>"
    allReleases: All releases
  ru:
    about: О проекте
    other: Другое
    discussion: Обсуждение
    toUp: Вверх
    insteadmanSubtitle: Играйте в текстовые приключения для INSTEAD!
    installInsteadman: Установите InsteadMan
    windowsDownloadText: В виде <strong>exe</strong>-установщика. Просто установите и запускайте.
    windowsDownloadText2: Также доступен просто <a href="_downloadUrl_">ZIP-архив</a> (запустите <strong>insteadman.exe</strong>).
    macosDownloadText: В виде <strong>dmg</strong>-образа. Откройте и перетащите в папку с приложениями.
    linuxDownloadText: В виде архива с бинарниками. Выберите архив для своей версии. Затем запустите <strong>./insteadman</strong>.<br>В системе должен быть установлен <a href="_insteadUrl_">INSTEAD <span class="glyphicon glyphicon-link"></span></a>.
    download: Загрузить
    result: Итог
    resultText: Вы сможете легко устанавливать и запускать игры!
    siteSupport: Поддержка сайта
    insteadSiteUrl: http://instead.syscall.ru/ru/index.html
    releaseNotes: "<ul><li>поправлен баг, когда нельзя было установить и запустить игру на Windows;</li><li>изменена сортировка игр: игры URQ в конце;</li><li>поправлены другие незначительные баги.</li></ul>"
    allReleases: Все релизы

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      lang: ru
      l: "" # lang for URL

  -
    scope:
      path: en
    values:
      lang: en
      l: /en
