# Site settings
title: InsteadMan
email: jhekasoft@gmail.com
description: InsteadMan is manager for INSTEAD games
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://instead.club" # the base hostname & protocol for your site
twitter_username: jhekasoft
github_username:  jhekasoft
asset_version: 1

t:
  en:
    about: About
    other: Other
    discussion: Discussion
    toUp: Up
    insteadmanSubtitle: Play text adventures for INSTEAD!
    installInsteadman: Install InsteadMan
    windowsDownloadText: Presented by <strong>exe</strong>-installation file. Just install and play.
    windowsDownloadText2: Also available <a href="https://yadi.sk/d/9lweXlGakUhoT">ZIP archive</a> (run <strong>insteadman.exe</strong>).
    macosDownloadText: Presented by <strong>dmg</strong> image. Open and drag it to the <strong>Applications</strong> folder.
    linuxDownloadText: Presented by archive with binaries. Please select proper archive for your OS. Then run <strong>./insteadman</strong>.<br>You should have installed <strong>INSTEAD</strong>.
    download: Download
    result: Result
    resultText: You able to install and play games easy!
  ru:
    about: О проекте
    other: Другое
    discussion: Обсуждение
    toUp: Вверх
    insteadmanSubtitle: Играйте в текстовые приключения для INSTEAD!
    installInsteadman: Установите InsteadMan
    windowsDownloadText: В виде <strong>exe</strong>-установщика. Просто установите и запускайте.
    windowsDownloadText2: Также доступен просто <a href="https://yadi.sk/d/9lweXlGakUhoT">ZIP-архив</a> (запустите <strong>insteadman.exe</strong>).
    macosDownloadText: В виде <strong>dmg</strong>-образа. Откройте и перетащите в папку с приложениями.
    linuxDownloadText: В виде архива с бинарниками. Выберети архив дя свой версии. Затем запустите <strong>./insteadman</strong>.<br>В системе должен быть установлен <strong>INSTEAD</strong>.
    download: Загрузить
    result: Итог
    resultText: Вы сможете легко устанавливать и запускать игры!


# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      lang: ru
      l: "" # lang for URL

  -
    scope:
      path: en
    values:
      lang: en
      l: /en
